In [1]:
#installing pandas
!pip install pandas

Requirement already satisfied: pandas in c:\users\jonar\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\jonar\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jonar\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jonar\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jonar\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\jonar\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
#installing numpy
!pip install numpy

Requirement already satisfied: numpy in c:\users\jonar\anaconda3\lib\site-packages (1.26.4)

In [3]:
#importing pandas in my current db that i'm working with
import pandas as pd

In [4]:
#importing numpy in my current db that i'm working with
import numpy as np

In [5]:
#reading the csv into my database
weather_data_1=pd.read_csv("c:/users/jonar/data/weather_data.csv")

In [6]:
#reading first 10 records of the weather dataset
weather_data_1.head(10)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89,7,6.4,101.29,Fog
7,1/1/2012 7:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,1/1/2012 8:00,-1.4,-3.6,85,9,8.0,101.23,Fog
9,1/1/2012 9:00,-1.3,-3.1,88,15,4.0,101.20,Fog

In [7]:
#finding all records where the weather was exactly clear
clear_weather = weather_data_1[weather_data_1['Weather']=='Clear']

clear_weather

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [8]:
#Finding the number of times the wind speed was exactly 4 km/hr
wind_speed = weather_data_1[weather_data_1['Wind Speed_km/h'] == 4]

wind_speed['Wind Speed_km/h'].count()

474

In [9]:
#checking if there are any null values present in the dataset
weather_data_1.info()
null_info = weather_data_1.isnull().sum()
print(null_info)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB
Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [10]:
#renaming 'Weather' to 'Weather_Condition'
weather_data_1.rename(columns={"Weather":"Weather_Condition"})

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather_Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [11]:
#mean visibility of the dataset
weather_data_1['Visibility_km'].mean()

27.664446721311478

In [12]:
#number of records where windspeed is greater than 24 km/hr and visibility equal to 25km
windspeed_visibility_check = weather_data_1[(weather_data_1['Wind Speed_km/h'] > 24) & (weather_data_1['Visibility_km'] == 25)]
windspeed_visibility_check.count()

Date/Time           308
Temp_C              308
Dew Point Temp_C    308
Rel Hum_%           308
Wind Speed_km/h     308
Visibility_km       308
Press_kPa           308
Weather             308
dtype: int64

In [13]:
#mean value of each column for each weather condition
mean_temp = weather_data_1['Temp_C'].mean()
mean_Dew_Point_Temp_C =weather_data_1['Dew Point Temp_C'].mean()
mean_Rel_Hum = weather_data_1['Rel Hum_%'].mean()
mean_Wind_Speed = weather_data_1['Wind Speed_km/h'].mean()
mean_Visibility_km = weather_data_1['Visibility_km'].mean()
mean_Press_kPa = weather_data_1['Press_kPa'].mean()
print('Mean_Temp_C: ', mean_temp)
print('Mean_Dew_Point_Temp_C: ', mean_Dew_Point_Temp_C )
print('Mean_Rel_Hum_%: ', mean_Rel_Hum )
print('Mean_Wind_Speed: ', mean_Wind_Speed)
print('Mean_Visibility_km: ', mean_Visibility_km )
print('Mean_Press_kPa: ', mean_Press_kPa)

Mean_Temp_C:  8.798144353369764
Mean_Dew_Point_Temp_C:  2.5552937158469944
Mean_Rel_Hum_%:  67.43169398907104
Mean_Wind_Speed:  14.94546903460838
Mean_Visibility_km:  27.664446721311478
Mean_Press_kPa:  101.05162340619307

In [20]:
#instances where the weather is clear and the relative humidity is greater than 50, or visibility is above 40
clear_humidity_visibility=weather_data_1[(weather_data_1['Weather']== 'Clear') & ((weather_data_1['Rel Hum_%'] > 50) | (weather_data_1['Visibility_km'] > 40))]
clear_humidity_visibility

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
241,1/11/2012 1:00,-10.7,-17.8,56,17,25.0,101.49,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [24]:
#Find the number of weather conditions that include snow
snowy_weather = weather_data_1 [weather_data_1['Weather'] == 'Snow']
snowy_weather['Weather'].count()

390